/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package christmas.lights.kata;

import java.util.HashMap;

public class ChristmasKataApp {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ChristmasGrid grid = new ChristmasGrid();
        grid.createGrid();
        grid.turnOnLights(new Coordinate(887,9),new Coordinate(959,629));
        grid.turnOnLights(new Coordinate(454,398  ),new Coordinate(844,448));
        grid.turnOffLights(new Coordinate(539,243),new Coordinate(559,965));
        grid.turnOffLights(new Coordinate(370,819),new Coordinate(676,868));
        grid.turnOffLights(new Coordinate(145,40 ),new Coordinate(370,997));
        grid.turnOffLights(new Coordinate(301,3),new Coordinate(808,453));
        grid.turnOnLights(new Coordinate(351,678 ),new Coordinate(951,908));
        grid.toggleLights(new Coordinate(720,196 ),new Coordinate(897,994));
        grid.toggleLights(new Coordinate(831,394 ),new Coordinate(904,860));

        System.out.println(grid.lightsCounter());

    }
}
