/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package christmas.lights.kata;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ChristmasKataAppTest {
    @Test void appHasAGreeting() {
        ChristmasKataApp classUnderTest = new ChristmasKataApp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
